fix: resolve service callout links with useBaseUrl hook
opentelekomcloud/docs-next pull request #145
Opened 2024-10-22 13:50 UTC by MJZLOTR

2024-10-24 06:04 UTC, akyriako requested changes
@MJZLOTR  Add the same thing to the button "Explore our Best Practices" in the landing page

2024-11-26 07:03 UTC, akyriako commented
@MJZLOTR the fix is missing still in some spots!

2024-11-28 13:11 UTC, MJZLOTR commented
@akyriako It seems like that the PR Preview Action is disabled.

2024-12-03 13:19 UTC, akyriako approved these changes

2024-12-03 13:20 UTC, merged